In [1]:
import pandas as pd
df = pd.read_csv('D:\FastAPI-Learning\Indian_Food_Nutrition_Processed.csv')

<>:2: SyntaxWarning: invalid escape sequence '\F'
<>:2: SyntaxWarning: invalid escape sequence '\F'
C:\Users\ravia\AppData\Local\Temp\ipykernel_19368\1033673897.py:2: SyntaxWarning: invalid escape sequence '\F'
  df = pd.read_csv('D:\FastAPI-Learning\Indian_Food_Nutrition_Processed.csv')

In [2]:
df

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg),Folate (µg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,3.12,14.20,0.02,0.50,1.80
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,4.92,20.87,0.06,1.51,5.60
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,13.98,58.10,0.15,1.51,5.53
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,0.23,1.18,0.02,5.95,1.28
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,79.82,7.08,0.14,45.30,14.05
...,...,...,...,...,...,...,...,...,...,...,...,...
1009,Sweet and sour tomato pickle (Khatta meetha ta...,60.88,6.55,1.26,3.24,4.31,2.20,1281.94,15.18,0.54,NaN,NaN
1010,Jhatpat achar with carrot (Jhatpat achaar gaja...,91.21,6.32,1.98,6.55,3.04,5.08,2067.33,54.31,2.32,NaN,NaN
1011,Tomato chutney (Tamatar ki chutney),176.07,31.85,0.97,6.01,30.02,1.49,823.65,25.34,0.96,NaN,NaN
1012,Tomato ketchup,33.07,6.48,0.91,0.30,4.68,1.90,177.97,15.33,0.36,NaN,NaN
1013,Bengal 5 Spice Blend (Panch Phoran),289.79,20.00,18.26,22.16,1.40,18.40,51.43,523.00,13.37,NaN,NaN

In [6]:
df.drop(columns=['Calories (kcal)','Free Sugar (g)','Fibre (g)','Sodium (mg)','Calcium (mg)','Iron (mg)','Vitamin C (mg)'], inplace=True)

In [7]:
df

,Dish Name,Carbohydrates (g),Protein (g),Fats (g),Folate (µg)
0,Hot tea (Garam Chai),2.58,0.39,0.53,1.80
1,Instant coffee,3.65,0.64,0.75,5.60
2,Espreso coffee,6.62,1.75,2.14,5.53
3,Iced tea,2.70,0.03,0.01,1.28
4,Raw mango drink (Aam panna),9.05,0.16,0.03,14.05
...,...,...,...,...,...
1009,Sweet and sour tomato pickle (Khatta meetha ta...,6.55,1.26,3.24,NaN
1010,Jhatpat achar with carrot (Jhatpat achaar gaja...,6.32,1.98,6.55,NaN
1011,Tomato chutney (Tamatar ki chutney),31.85,0.97,6.01,NaN
1012,Tomato ketchup,6.48,0.91,0.30,NaN
1013,Bengal 5 Spice Blend (Panch Phoran),20.00,18.26,22.16,NaN

In [8]:
df.drop(columns=['Folate (µg)'],inplace=True)

In [9]:
df.head()

                     Dish Name  Carbohydrates (g)  Protein (g)  Fats (g)
0         Hot tea (Garam Chai)               2.58         0.39      0.53
1               Instant coffee               3.65         0.64      0.75
2               Espreso coffee               6.62         1.75      2.14
3                     Iced tea               2.70         0.03      0.01
4  Raw mango drink (Aam panna)               9.05         0.16      0.03

In [10]:
df.to_csv('D:\FastAPI-Learning\Indian_Food_Nutrition_Processed_Cleaned.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\F'
C:\Users\ravia\AppData\Local\Temp\ipykernel_19368\3885879100.py:1: SyntaxWarning: invalid escape sequence '\F'
  df.to_csv('D:\FastAPI-Learning\Indian_Food_Nutrition_Processed_Cleaned.csv', index=False)

In [2]:
import pandas as pd
df = pd.read_csv('D:\FastAPI-Learning\Indian_Food_Nutrition_Processed_Cleaned.csv')

<>:2: SyntaxWarning: invalid escape sequence '\F'
<>:2: SyntaxWarning: invalid escape sequence '\F'
C:\Users\ravia\AppData\Local\Temp\ipykernel_11664\2777740157.py:2: SyntaxWarning: invalid escape sequence '\F'
  df = pd.read_csv('D:\FastAPI-Learning\Indian_Food_Nutrition_Processed_Cleaned.csv')

In [3]:
df.head()

                     Dish Name  Carbohydrates (g)  Protein (g)  Fats (g)
0         Hot tea (Garam Chai)               2.58         0.39      0.53
1               Instant coffee               3.65         0.64      0.75
2               Espreso coffee               6.62         1.75      2.14
3                     Iced tea               2.70         0.03      0.01
4  Raw mango drink (Aam panna)               9.05         0.16      0.03

In [ ]:
Protein: 1.98 g Carbs: 5.49 g Fat: 84.11 g

In [4]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
carbs = float(input("Enter Carbohydrates (g): "))
protein = float(input("Enter Protein (g): "))
fat = float(input("Enter Fats (g): "))

X = df[["Carbohydrates (g)", "Protein (g)", "Fats (g)"]].values
target = [[carbs, protein, fat]]

# Cosine similarity
similarity_scores = cosine_similarity(target, X)[0]

# Get top 5 indices sorted by similarity
top_5_indices = similarity_scores.argsort()[-5:][::-1]

# Print results
print("\n✅ Top 5 Most Similar Dishes (Cosine Similarity):\n")
for idx in top_5_indices:
    dish = df.iloc[idx]
    score = similarity_scores[idx] * 100
    print(f"{dish['Dish Name']} — Similarity: {score:.2f}%")

✅ Top 5 Most Similar Dishes (Cosine Similarity):

Spinach pakora/pakoda (Palak pakoda) — Similarity: 100.00%
Crispy okra/Crispy lady's fingers (Karare bhindi) — Similarity: 100.00%
Methi pakora/pakoda (Methi ke pakode) — Similarity: 100.00%
Cauliflower pakora/pakoda (Phoolgobhi ke pakode) — Similarity: 100.00%
Cheese toast — Similarity: 100.00%